### ISSUE TITLE
Problems with validations not stopping submit

### ISSUE THREAD

**Issue by dotbear** [musicglue/react-form-component#2]
Second time you press "save" it runs the submithandler even though there are outstanding validation errors.

**Comment by dotbear** [comment]
@jgwmaxwell is this something anyone is aware of?

**Comment by peterhorne** [comment]
It's because `validateOutstanding` doesn't set the disabled state if there are any additional errors.

**Comment by jgwmaxwell** [comment]
probably better fiiiiiiiiix iiiiiiiit :)
